
name: Build and deploy container app to Azure Web App - tendrs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: 
          username: 
          password: 

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: 
          file: ./Dockerfile
          
            
  